spring.application.name=userservice
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_AI_db
spring.datasource.username=postgres
spring.datasource.password=0421
spring.jpa.hibernate.ddl-auto=update
server.port=8088
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/